### PR TITLE
Add  -x flag to prevent script execution. New text for log messages.

### PR DESCRIPTION
**Pull request by marjohn56**
dhcp6c will launch th script  specified in the config files on receipt
of a reply from the dhcp6 server. In certain circumstances this is not
requred, namely where rtsold runs after dhcp6c ( certain ISP's require
this ) and calls the same script. This additional flag prevents dhcp6c
from running the script only when it receives a REPLY signal from the
server. As the REPLY signal is only sent when replying to a REQUEST, and
as the REQUEST is only sent at the start of a session then any other
trigger to run the script will execute it as normal.

Changed log messages  to better reflect response messages, Received REQUEST now logs Received Reply etc.

### CODE REVIEW

**Comment by hrs-allbsd** [comment]
What sequence of DHCPv6 and RA is used to configure the IPv6 link to the ISP?  I would like to know it before adding a new option.

**Comment by marjohn56** [comment]
Most ISP’s are normal and work with RA before dhcp6, some, including mine ( Sky UK) have done it the other way and require dhcp6 before RA.

In the normal case where the ISP requires RA before DHCP then you would not use the -x flag, as when dhcp6c gets the reply you want to call the update script.

 In the ‘abnormal’ ISP case the dhcp6 request is sent before the RS. In this case the RA arrives after the dhcp6 reply and if the script is left to run then when the RA signal arrives, as in the case of pfSense, then RTSOLD will run the same script before the first run of the script launched by dhpc6 has completed. So in the latter case you would set the -x flag to prevent dhcp6 from running the script as RTSOLD will do that when the RA signal arrives.

 Does that make sense?

**Comment by rbgarga** [comment]
@marjohn56 you should submit your patch against branch 'freebsd' instead of 'master', otherwise it's going to modify a lot of files with no reason

**Comment by marjohn56** [comment]
Nut's, I saw that and thought I had. Kill this PR and I'll resubmit on the correct one.

**Pull request closed without merging**
